// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: grpc/purpose.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Payout    uint64 `protobuf:"varint,2,opt,name=payout,proto3" json:"payout,omitempty"`
	Completed bool   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
}

func (x *Mission) Reset() {
	*x = Mission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_purpose_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_purpose_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_grpc_purpose_proto_rawDescGZIP(), []int{0}
}

func (x *Mission) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mission) GetPayout() uint64 {
	if x != nil {
		return x.Payout
	}
	return 0
}

func (x *Mission) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type MissionStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MissionStreamRequest) Reset() {
	*x = MissionStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_purpose_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissionStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionStreamRequest) ProtoMessage() {}

func (x *MissionStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_purpose_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionStreamRequest.ProtoReflect.Descriptor instead.
func (*MissionStreamRequest) Descriptor() ([]byte, []int) {
	return file_grpc_purpose_proto_rawDescGZIP(), []int{1}
}

type MissionStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Missions []*Mission `protobuf:"bytes,2,rep,name=missions,proto3" json:"missions,omitempty"`
}

func (x *MissionStreamResponse) Reset() {
	*x = MissionStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_purpose_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissionStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionStreamResponse) ProtoMessage() {}

func (x *MissionStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_purpose_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionStreamResponse.ProtoReflect.Descriptor instead.
func (*MissionStreamResponse) Descriptor() ([]byte, []int) {
	return file_grpc_purpose_proto_rawDescGZIP(), []int{2}
}

func (x *MissionStreamResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MissionStreamResponse) GetMissions() []*Mission {
	if x != nil {
		return x.Missions
	}
	return nil
}

type AddMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mission *Mission `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
}

func (x *AddMissionRequest) Reset() {
	*x = AddMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_purpose_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMissionRequest) ProtoMessage() {}

func (x *AddMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_purpose_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMissionRequest.ProtoReflect.Descriptor instead.
func (*AddMissionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_purpose_proto_rawDescGZIP(), []int{3}
}

func (x *AddMissionRequest) GetMission() *Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

type AddMissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddMissionResponse) Reset() {
	*x = AddMissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_purpose_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMissionResponse) ProtoMessage() {}

func (x *AddMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_purpose_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMissionResponse.ProtoReflect.Descriptor instead.
func (*AddMissionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_purpose_proto_rawDescGZIP(), []int{4}
}

type RemoveMissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mission *Mission `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
}

func (x *RemoveMissionRequest) Reset() {
	*x = RemoveMissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_purpose_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMissionRequest) ProtoMessage() {}

func (x *RemoveMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_purpose_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMissionRequest.ProtoReflect.Descriptor instead.
func (*RemoveMissionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_purpose_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveMissionRequest) GetMission() *Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

type RemoveMissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveMissionResponse) Reset() {
	*x = RemoveMissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_purpose_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMissionResponse) ProtoMessage() {}

func (x *RemoveMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_purpose_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMissionResponse.ProtoReflect.Descriptor instead.
func (*RemoveMissionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_purpose_proto_rawDescGZIP(), []int{6}
}

var File_grpc_purpose_proto protoreflect.FileDescriptor

var file_grpc_purpose_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x22, 0x55, 0x0a,
	0x07, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x70, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x15,
	0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x75,
	0x72, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3f, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x42,
	0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73,
	0x65, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf8, 0x01, 0x0a, 0x07,
	0x50, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1d, 0x2e, 0x70, 0x75, 0x72, 0x70, 0x6f,
	0x73, 0x65, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73,
	0x65, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x47, 0x0a, 0x0a, 0x41,
	0x64, 0x64, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x70, 0x75, 0x72, 0x70,
	0x6f, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x2e,
	0x41, 0x64, 0x64, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_purpose_proto_rawDescOnce sync.Once
	file_grpc_purpose_proto_rawDescData = file_grpc_purpose_proto_rawDesc
)

func file_grpc_purpose_proto_rawDescGZIP() []byte {
	file_grpc_purpose_proto_rawDescOnce.Do(func() {
		file_grpc_purpose_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_purpose_proto_rawDescData)
	})
	return file_grpc_purpose_proto_rawDescData
}

var file_grpc_purpose_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grpc_purpose_proto_goTypes = []interface{}{
	(*Mission)(nil),               // 0: purpose.Mission
	(*MissionStreamRequest)(nil),  // 1: purpose.MissionStreamRequest
	(*MissionStreamResponse)(nil), // 2: purpose.MissionStreamResponse
	(*AddMissionRequest)(nil),     // 3: purpose.AddMissionRequest
	(*AddMissionResponse)(nil),    // 4: purpose.AddMissionResponse
	(*RemoveMissionRequest)(nil),  // 5: purpose.RemoveMissionRequest
	(*RemoveMissionResponse)(nil), // 6: purpose.RemoveMissionResponse
}
var file_grpc_purpose_proto_depIdxs = []int32{
	0, // 0: purpose.MissionStreamResponse.missions:type_name -> purpose.Mission
	0, // 1: purpose.AddMissionRequest.mission:type_name -> purpose.Mission
	0, // 2: purpose.RemoveMissionRequest.mission:type_name -> purpose.Mission
	1, // 3: purpose.Purpose.MissionStream:input_type -> purpose.MissionStreamRequest
	3, // 4: purpose.Purpose.AddMission:input_type -> purpose.AddMissionRequest
	5, // 5: purpose.Purpose.RemoveMission:input_type -> purpose.RemoveMissionRequest
	2, // 6: purpose.Purpose.MissionStream:output_type -> purpose.MissionStreamResponse
	4, // 7: purpose.Purpose.AddMission:output_type -> purpose.AddMissionResponse
	6, // 8: purpose.Purpose.RemoveMission:output_type -> purpose.RemoveMissionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_purpose_proto_init() }
func file_grpc_purpose_proto_init() {
	if File_grpc_purpose_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_purpose_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_purpose_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissionStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_purpose_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissionStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_purpose_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_purpose_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_purpose_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_purpose_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveMissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_purpose_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_purpose_proto_goTypes,
		DependencyIndexes: file_grpc_purpose_proto_depIdxs,
		MessageInfos:      file_grpc_purpose_proto_msgTypes,
	}.Build()
	File_grpc_purpose_proto = out.File
	file_grpc_purpose_proto_rawDesc = nil
	file_grpc_purpose_proto_goTypes = nil
	file_grpc_purpose_proto_depIdxs = nil
}
